In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = pd.read_csv('/content/titanic_dataset.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
#2.Make ‘PassengerId’ as the index column
data.set_index('PassengerId', inplace=True)

In [5]:
data.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
#3.Check the basic details of the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

In [7]:
#4.Fill in all the missing values present in all the columns in the dataset
data.fillna(method='ffill', inplace=True)

In [8]:
data.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C85,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,C123,S

In [ ]:
#5.Check and handle outliers in at least 3 columns in the dataset
# Handling outliers in 'Age' column
age_mean = data['Age'].mean()
age_std = data['Age'].std()
age_cutoff = age_mean + 3 * age_std
data.loc[data['Age'] > age_cutoff, 'Age'] = age_cutoff

In [61]:
# Handling outliers in 'Fare' column
fare_cutoff = data['Fare'].quantile(0.90)
data.loc[data['Fare'] > fare_cutoff, 'Fare'] = fare_cutoff

In [59]:

# Handling outliers in 'SibSp' column
sibsp_cutoff = 4
data.loc[data['SibSp'] > sibsp_cutoff, 'SibSp'] = sibsp_cutoff

In [62]:
data.head()

,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Pclass_1,Pclass_2,Pclass_3
PassengerId,,,,,,,,,,,,,,,,
1,0,"Braund, Mr. Owen Harris",22.0,1.0,0,A/5 21171,7.250,NaN,False,True,False,False,True,False,False,True
2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1.0,0,PC 17599,53.100,C85,True,False,True,False,False,True,False,False
3,1,"Heikkinen, Miss. Laina",26.0,0.0,0,STON/O2. 3101282,7.925,C85,True,False,False,False,True,False,False,True
4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1.0,0,113803,53.100,C123,True,False,False,False,True,True,False,False
5,0,"Allen, Mr. William Henry",35.0,0.0,0,373450,8.050,C123,False,True,False,False,True,False,False,True

In [65]:
#6.Do min max scaling on the feature set (Take ‘Survived’ as target)
from sklearn.preprocessing import MinMaxScaler
X = data.drop('Survived', axis=1)
y = data['Survived']

In [72]:
data = data

In [73]:
print(X.dtypes)

Age           float64
SibSp         float64
Parch           int64
Ticket         object
Fare          float64
Cabin          object
Sex_female       bool
Sex_male         bool
Embarked_C       bool
Embarked_Q       bool
Embarked_S       bool
Pclass_1         bool
Pclass_2         bool
Pclass_3         bool
dtype: object

In [81]:
X = X.drop(columns=['Cabin', 'Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q',	'Embarked_S',	'Pclass_1',	'Pclass_2',	'Pclass_3'])

In [82]:
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [83]:
X_scaled

array([[0.30575234, 1.        , 0.        , 0.13653484],
       [0.53244545, 1.        , 0.        , 1.        ],
       [0.36242562, 0.        , 0.        , 0.1492467 ],
       ...,
       [0.26324738, 1.        , 0.33333333, 0.44161959],
       [0.36242562, 0.        , 0.        , 0.56497175],
       [0.44743553, 0.        , 0.        , 0.14595104]])